// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ptik struct {
	ID           int32
	NoUrut       int16
	Nama         string
	TempatLahir  string
	TanggalLahir pgtype.Date
	Angkatan     int16
	Password     pgtype.Text
	Pfp          pgtype.Text
}

type Tuga struct {
	ID        int32
	Nama      string
	Matkul    string
	Deskripsi string
	Deadline  pgtype.Date
	Link      pgtype.Text
}
