// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUser = `-- name: CheckUser :one
select id, angkatan, password from ptik where no_urut = $1 and angkatan = $2
`

type CheckUserParams struct {
	NoUrut   int16
	Angkatan int16
}

type CheckUserRow struct {
	ID       int32
	Angkatan int16
	Password pgtype.Text
}

func (q *Queries) CheckUser(ctx context.Context, arg CheckUserParams) (CheckUserRow, error) {
	row := q.db.QueryRow(ctx, checkUser, arg.NoUrut, arg.Angkatan)
	var i CheckUserRow
	err := row.Scan(&i.ID, &i.Angkatan, &i.Password)
	return i, err
}

const createTugas = `-- name: CreateTugas :exec
insert into tugas (nama, matkul, deskripsi, deadline, link) values ($1, $2, $3, $4, $5)
`

type CreateTugasParams struct {
	Nama      string
	Matkul    string
	Deskripsi string
	Deadline  pgtype.Date
	Link      pgtype.Text
}

func (q *Queries) CreateTugas(ctx context.Context, arg CreateTugasParams) error {
	_, err := q.db.Exec(ctx, createTugas,
		arg.Nama,
		arg.Matkul,
		arg.Deskripsi,
		arg.Deadline,
		arg.Link,
	)
	return err
}

const getTugas = `-- name: GetTugas :one
select id, nama, matkul, deskripsi, deadline, link from tugas where id = $1
`

func (q *Queries) GetTugas(ctx context.Context, id int32) (Tuga, error) {
	row := q.db.QueryRow(ctx, getTugas, id)
	var i Tuga
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Matkul,
		&i.Deskripsi,
		&i.Deadline,
		&i.Link,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, CONCAT('K35', RIGHT(angkatan::text, 2), LPAD(no_urut::text, 3, '0')) as nim, nama, tempat_lahir, tanggal_lahir, angkatan, pfp from ptik where id = $1
`

type GetUserRow struct {
	ID           int32
	Nim          interface{}
	Nama         string
	TempatLahir  string
	TanggalLahir pgtype.Date
	Angkatan     int16
	Pfp          pgtype.Text
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Nim,
		&i.Nama,
		&i.TempatLahir,
		&i.TanggalLahir,
		&i.Angkatan,
		&i.Pfp,
	)
	return i, err
}

const listPTIK = `-- name: ListPTIK :many
select id, CONCAT('K35', RIGHT(angkatan::text, 2), LPAD(no_urut::text, 3, '0')) as nim, nama, tempat_lahir, tanggal_lahir, angkatan from ptik where angkatan = $1 order by no_urut
`

type ListPTIKRow struct {
	ID           int32
	Nim          interface{}
	Nama         string
	TempatLahir  string
	TanggalLahir pgtype.Date
	Angkatan     int16
}

func (q *Queries) ListPTIK(ctx context.Context, angkatan int16) ([]ListPTIKRow, error) {
	rows, err := q.db.Query(ctx, listPTIK, angkatan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPTIKRow
	for rows.Next() {
		var i ListPTIKRow
		if err := rows.Scan(
			&i.ID,
			&i.Nim,
			&i.Nama,
			&i.TempatLahir,
			&i.TanggalLahir,
			&i.Angkatan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTugas = `-- name: ListTugas :many
select id, nama, matkul, deskripsi, deadline, link from tugas where deadline >= CURRENT_DATE ORDER BY deadline
`

func (q *Queries) ListTugas(ctx context.Context) ([]Tuga, error) {
	rows, err := q.db.Query(ctx, listTugas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tuga
	for rows.Next() {
		var i Tuga
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Matkul,
			&i.Deskripsi,
			&i.Deadline,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTugasLama = `-- name: ListTugasLama :many
select id, nama, matkul, deskripsi, deadline, link from tugas where deadline < CURRENT_DATE ORDER BY deadline
`

func (q *Queries) ListTugasLama(ctx context.Context) ([]Tuga, error) {
	rows, err := q.db.Query(ctx, listTugasLama)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tuga
	for rows.Next() {
		var i Tuga
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Matkul,
			&i.Deskripsi,
			&i.Deadline,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
update ptik set password = $1 where no_urut = $2 and angkatan = $3 and tanggal_lahir = $4
`

type UpdatePasswordParams struct {
	Password     pgtype.Text
	NoUrut       int16
	Angkatan     int16
	TanggalLahir pgtype.Date
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword,
		arg.Password,
		arg.NoUrut,
		arg.Angkatan,
		arg.TanggalLahir,
	)
	return err
}

const updateTugas = `-- name: UpdateTugas :exec
update tugas set nama = $2, matkul = $3, deskripsi = $4, deadline = $5, link = $6 where id = $1
`

type UpdateTugasParams struct {
	ID        int32
	Nama      string
	Matkul    string
	Deskripsi string
	Deadline  pgtype.Date
	Link      pgtype.Text
}

func (q *Queries) UpdateTugas(ctx context.Context, arg UpdateTugasParams) error {
	_, err := q.db.Exec(ctx, updateTugas,
		arg.ID,
		arg.Nama,
		arg.Matkul,
		arg.Deskripsi,
		arg.Deadline,
		arg.Link,
	)
	return err
}
